server:
  port: 8088

# ********************** Feign start ********************** #
feign:
  client:
    config:
      default:
        loggerLevel: FULL

logging:
  level:
    feign.Logger: debug
# ********************** Feign start ********************** #